# Generated by Django 2.2 on 2020-03-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, verbose_name='email-id')),
                ('message', models.TextField(max_length=100, verbose_name='How can we help?')),
            ],
        ),
    ]
